"""create a temporary sqlite database

Revision ID: 32da32cb620f
Revises: 78935a09869f
Create Date: 2022-12-07 10:55:12.651146

"""

# revision identifiers, used by Alembic.
revision = '32da32cb620f'
down_revision = '78935a09869f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
