"""create a temporary sqlite database

Revision ID: 6bad1b0eb46e
Revises: aeead4687c79
Create Date: 2022-12-06 14:52:58.988929

"""

# revision identifiers, used by Alembic.
revision = '6bad1b0eb46e'
down_revision = 'aeead4687c79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
