"""create a temporary sqlite database

Revision ID: 78935a09869f
Revises: f75265c1c1fb
Create Date: 2022-12-07 10:10:42.314962

"""

# revision identifiers, used by Alembic.
revision = '78935a09869f'
down_revision = 'f75265c1c1fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
