"""create a temporary sqlite database

Revision ID: 7df18d51ca43
Revises: c1bc8df283b0
Create Date: 2022-11-25 08:26:38.820501

"""

# revision identifiers, used by Alembic.
revision = '7df18d51ca43'
down_revision = 'c1bc8df283b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('r_email', sa.String(length=64), nullable=True))
    op.drop_column('posts', 'r_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('r_name', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('posts', 'r_email')
    # ### end Alembic commands ###
