"""create a temporary sqlite database

Revision ID: 84ded2d282b8
Revises: 2e1ecc09beca
Create Date: 2022-12-10 18:47:10.756329

"""

# revision identifiers, used by Alembic.
revision = '84ded2d282b8'
down_revision = '2e1ecc09beca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('drivers', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'drivers')
    # ### end Alembic commands ###
