"""create a temporary sqlite database

Revision ID: a7bd2ec86b5f
Revises: e0a55fcfb0f2
Create Date: 2022-12-29 23:22:34.836972

"""

# revision identifiers, used by Alembic.
revision = 'a7bd2ec86b5f'
down_revision = 'e0a55fcfb0f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('statue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'statue')
    # ### end Alembic commands ###
