"""create a temporary sqlite database

Revision ID: c1bc8df283b0
Revises: 51f5ccfba190
Create Date: 2022-11-25 08:06:02.897961

"""

# revision identifiers, used by Alembic.
revision = 'c1bc8df283b0'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('destination', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('id_no', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('phone_no', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('r_name', sa.String(length=64), nullable=True))
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.drop_column('posts', 'r_name')
    op.drop_column('posts', 'quantity')
    op.drop_column('posts', 'phone_no')
    op.drop_column('posts', 'name')
    op.drop_column('posts', 'id_no')
    op.drop_column('posts', 'destination')
    # ### end Alembic commands ###
