"""create a temporary sqlite database

Revision ID: cb2089d76e03
Revises: 84ded2d282b8
Create Date: 2022-12-10 18:58:29.876306

"""

# revision identifiers, used by Alembic.
revision = 'cb2089d76e03'
down_revision = '84ded2d282b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('cities_start', sa.String(length=64), nullable=True))
    op.add_column('routes', sa.Column('cities_stop', sa.String(length=64), nullable=True))
    op.drop_column('routes', 'cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('cities', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('routes', 'cities_stop')
    op.drop_column('routes', 'cities_start')
    # ### end Alembic commands ###
