"""create a temporary sqlite database

Revision ID: f75265c1c1fb
Revises: 6bad1b0eb46e
Create Date: 2022-12-07 10:04:55.944571

"""

# revision identifiers, used by Alembic.
revision = 'f75265c1c1fb'
down_revision = '6bad1b0eb46e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
